# renderer configuration

bb_scripts_directory:
    common: %bbapp.base.dir%/Resources/scripts
    form: %bbapp.base.dir%/Form/Templates/scripts

adapter:
    - BackBuilder\Renderer\Adapter\Twig
    - BackBuilder\Renderer\Adapter\phtml

path:
    scriptdir: Templates/scripts
    layoutdir: Layouts
